name: Build & Deploy (Runner-in-server)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/lily-b-lee/security_dashboard:latest

  deploy:
    needs: build
    runs-on: self-hosted   # ← 또는 ["self-hosted","deploy-runner"]
    steps:
      - name: Pull and restart via compose
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPOSE_DIR: /home/posacuser/apps/security_dashboard
        run: |
          docker login ghcr.io -u "$GITHUB_ACTOR" -p "$GITHUB_TOKEN"
          cd "$COMPOSE_DIR"
          docker compose pull
          docker compose up -d
          docker image prune -f
